using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MqttControllerFramework.SourceGenerators;

/// <summary>
/// Generates Markdown documentation (embedded as a C# source comment) for all discovered MQTT controllers.
/// </summary>
[Generator]
public class MqttDocumentationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var docs = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetDoc(ctx))
            .Where(static d => d is not null);

        var combined = context.CompilationProvider.Combine(docs.Collect());
        context.RegisterSourceOutput(combined, static (spc, src) => Execute(src.Left, src.Right!, spc));
    }

    private static MqttControllerDoc? GetDoc(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol sym) return null;

        var attr = sym.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name is "MqttControllerAttribute" or "MqttController");
        if (attr == null) return null;

        var prefix = attr.ConstructorArguments.Length > 0
            ? attr.ConstructorArguments[0].Value?.ToString() ?? ""
            : "";

        var methods = sym.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary)
            .Select(m =>
            {
                var topicAttr = m.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name is "MqttTopicAttribute" or "MqttTopic");
                if (topicAttr == null) return null;
                var template = topicAttr.ConstructorArguments.Length > 0
                    ? topicAttr.ConstructorArguments[0].Value?.ToString() ?? ""
                    : "";
                var final = string.Join("/", new[] { prefix, template }.Where(s => !string.IsNullOrEmpty(s)));
                var summary = m.GetDocumentationCommentXml();
                return new MqttMethodDoc { MethodName = m.Name, TopicTemplate = final, XmlSummary = summary };
            })
            .Where(m => m != null)
            .ToList();

        if (methods.Count == 0) return null;

        return new MqttControllerDoc
        {
            ClassName = sym.Name,
            Namespace = sym.ContainingNamespace?.IsGlobalNamespace == false ? sym.ContainingNamespace.ToDisplayString() : null,
            Prefix = prefix,
            XmlSummary = sym.GetDocumentationCommentXml(),
            Methods = methods!
        };
    }

    private static void Execute(Compilation compilation, ImmutableArray<MqttControllerDoc> docs, SourceProductionContext ctx)
    {
        if (docs.Length == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// MQTT Controller Documentation");
        sb.AppendLine($"// Assembly: {compilation.AssemblyName}");
        sb.AppendLine("//");

        foreach (var doc in docs.OrderBy(d => d.ClassName))
        {
            sb.AppendLine($"// ## {doc.ClassName}");
            if (!string.IsNullOrEmpty(doc.Namespace)) sb.AppendLine($"// Namespace: {doc.Namespace}");
            if (!string.IsNullOrEmpty(doc.Prefix)) sb.AppendLine($"// Prefix: `{doc.Prefix}`");
            sb.AppendLine("//");
            sb.AppendLine("// | Method | Topic Template |");
            sb.AppendLine("// |--------|----------------|");
            foreach (var m in doc.Methods)
                sb.AppendLine($"// | `{m.MethodName}` | `{m.TopicTemplate}` |");
            sb.AppendLine("//");
        }

        // Empty class so the source file is valid C#
        sb.AppendLine($"namespace {compilation.AssemblyName}.Mqtt.Generated {{ }}");

        ctx.AddSource("_MqttDocumentation.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private class MqttControllerDoc
    {
        public string ClassName { get; set; } = "";
        public string? Namespace { get; set; }
        public string Prefix { get; set; } = "";
        public string? XmlSummary { get; set; }
        public List<MqttMethodDoc> Methods { get; set; } = new();
    }

    private class MqttMethodDoc
    {
        public string MethodName { get; set; } = "";
        public string TopicTemplate { get; set; } = "";
        public string? XmlSummary { get; set; }
    }
}
